name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs Every Day
  workflow_dispatch:

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: '@sangyk' 
          COUNT: 3 
          STYLE: "blog-left"
          FILE: "53a45644150ff39cc6231c97fa0b3d3b" # GIST ID
          TYPE: "gist"
          BLOG_URL: "https://theintrovertcoder.hashnode.dev/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
